# Site settings
title: Lorem Ipsum - Web Developer
description: "Android 从入门到放弃_(:зゝ∠)_"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://anzj.github.io"

# User settings
username: Zhao Jie
user_title: user_title
email: oaierp@gmail.com
twitter_username: Olvep
github_username:  anzj
gplus_username:  oaierp
disqus_username: loremipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: About me
    url: /about
# projects in header index
projects:
  - name: asciilang
    url: https://github.com/victorvoid/asciilang
  - name: vim-frontend
    url: https://github.com/victorvoid/vim-frontend
  - name: generator-capybara
    url: https://github.com/victorvoid/generator-capybara 
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
